rem Exports the core of the MSVC environment to the GitHub Actions environment block
echo "CommandPromptType=%CommandPromptType%" >> $GITHUB_ENV
echo "DevEnvDir=%DevEnvDir%" >> $GITHUB_ENV
echo "ExtensionSdkDir=%ExtensionSdkDir%" >> $GITHUB_ENV
echo "INCLUDE=%INCLUDE%" >> $GITHUB_ENV
echo "LIB=%LIB%" >> $GITHUB_ENV
echo "LIBPATH=%LIBPATH%" >> $GITHUB_ENV
echo "PATH=C:\Program Files\OpenCppCoverage;%PATH%" >> $GITHUB_ENV
echo "Platform=%Platform%" >> $GITHUB_ENV
echo "UCRTVersion=%UCRTVersion%" >> $GITHUB_ENV
echo "UniversalCRTSdkDir=%UniversalCRTSdkDir%" >> $GITHUB_ENV
echo "VCINSTALLDIR=%VCINSTALLDIR%" >> $GITHUB_ENV
echo "VCToolsInstallDir=%VCToolsInstallDir%" >> $GITHUB_ENV
echo "VCToolsRedistDir=%VCToolsRedistDir%" >> $GITHUB_ENV
echo "VCToolsVersion=%VCToolsVersion%" >> $GITHUB_ENV
echo "VisualStudioVersion=%VisualStudioVersion%" >> $GITHUB_ENV
echo "VSINSTALLDIR=%VSINSTALLDIR%" >> $GITHUB_ENV
echo "WindowsLibPath=%WindowsLibPath%" >> $GITHUB_ENV
echo "WindowsSdkBinPath=%WindowsSdkBinPath%" >> $GITHUB_ENV
echo "WindowsSdkDir=%WindowsSdkDir%" >> $GITHUB_ENV
echo "WindowsSDKLibVersion=%WindowsSDKLibVersion%" >> $GITHUB_ENV
echo "WindowsSdkVerBinPath=%WindowsSdkVerBinPath%" >> $GITHUB_ENV
echo "WindowsSDKVersion=%WindowsSDKVersion%" >> $GITHUB_ENV
echo "WindowsSDK_ExecutablePath_x64=%WindowsSDK_ExecutablePath_x64%" >> $GITHUB_ENV
echo "WindowsSDK_ExecutablePath_x86=%WindowsSDK_ExecutablePath_x86%" >> $GITHUB_ENV
echo "CPU_COUNT=%NUMBER_OF_PROCESSORS%" >> $GITHUB_ENV
