source "https://rubygems.org"

gem "jekyll"

# If you have any plugins, put them here!
group :jekyll_plugins do
	gem "jekyll-github-metadata"
	gem "jekyll-theme-midnight"
	gem "jekyll-titles-from-headings"
	gem "jekyll-relative-links"
	gem "jekyll-readme-index"
	gem "jekyll-optional-front-matter"
	gem "jekyll-default-layout"
	gem "jekyll-seo-tag"
	gem "jekyll-font-awesome-sass"
end

gem "font-awesome-sass"
gem "kramdown"
gem "rouge"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

