#!/bin/bash -e

if [ $# -ne 1 ]; then
	echo "Must provide the name of the dist archive to package"
	exit 1
fi

rpmdev-setuptree
cp ${1}{,.asc} ~/rpmbuild/SOURCES
cp crunch.spec ~/rpmbuild/SPECS

rpmbuild -ba --sign ~/rpmbuild/SPECS/crunch.spec

cp ~/rpmbuild/RPMS/x86_64/crunch-*.rpm /data/crunch/package
cp ~/rpmbuild/SRPMS/crunch-*.src.rpm /data/crunch/package
